Projects
ufosc/ALBot-2.0 pull request #21
Opened 2022-04-04 23:19 UTC by devp4

2022-04-11 20:39 UTC, skbt27i commented
It looks mostly good, but we should make sure that the assigned role is never an officer, and you could also check if the role is "open" (/roles command will tell you which are, and /openrole <rolename> will open a role).

2022-04-11 20:41 UTC, skbt27i requested changes
check if role is "open"

2022-04-14 19:56 UTC, devp4 commented
Current bug: if two users use /projects and one person clicks on a button, it triggers button for both users

2022-04-14 20:51 UTC, skbt27i commented
are you able to fix that?

2022-04-14 20:51 UTC, skbt27i approved these changes

2022-04-17 00:55 UTC, skbt27i approved these changes

2022-04-17 00:57 UTC, skbt27i commented on src/projects.json
> +                "value": "[Intro to TypeScript](https://youtu.be/gp5H0Vw39yw)\n[Discord.js Documentation](https://discord.js.org/#/)\n[Discrod.js Guide](https://discordjs.guide/#before-you-begin)",
small typo here

2022-04-17 00:59 UTC, skbt27i approved these changes

2022-04-18 01:04 UTC, merged